-- ═══════════════════════════════════════════════════════════════════
--  BigBoomEvents — catalog BALOANE & ACCESORII PARTY (iulie 2026)
--  Sursă: „party shop 1.xlsx" + „pachete baloane.xlsx".
--  SIGUR pe prod: atinge DOAR categoria 'baloane' + add-on-urile heliu/party.
--  Rulează întâi schema.sql (adaugă product_type + addon_scope), apoi acesta:
--    node scripts/run-sql.js db/schema.sql
--    node scripts/run-sql.js db/seed-baloane-2026-07.sql
--  Preț de bază = FĂRĂ heliu (cu aer / set / ridicare). Heliul = add-on separat
--  (opțiune pe pagina produsului, ca șampania) cu pop-up „livrare doar în Iași".
--  Cele 7 seturi fără preț în Excel intră is_active=FALSE (nevândabile până la preț).
-- ═══════════════════════════════════════════════════════════════════

BEGIN;

-- coloane idempotente (dacă schema.sql n-a rulat)
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_type TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS addon_scope  TEXT[];

-- ─── 1. Produsele din Excel (upsert idempotent pe slug) ───
INSERT INTO products
  (slug, name, description, category_id, price_cents, old_price_cents, stock,
   badge, occasions, colors, images, is_active, product_type, is_addon)
VALUES
  ('balon-latex-alb',
   'Balon latex Alb',
   'Balon din latex, culoare alb, diametru 30 cm.',
   (SELECT id FROM categories WHERE slug='baloane'),
   3500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['alb'],
   ARRAY['/assets/products/balon-latex-alb.webp'], TRUE, 'baloane-latex', FALSE),
  ('balon-latex-albastru',
   'Balon latex Albastru',
   'Balon din latex, culoare albastru, diametru 30 cm.',
   (SELECT id FROM categories WHERE slug='baloane'),
   3500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['alb','albastru'],
   ARRAY['/assets/products/balon-latex-albastru.webp'], TRUE, 'baloane-latex', FALSE),
  ('balon-latex-argintiu',
   'Balon latex Argintiu',
   'Balon din latex, culoare argintiu, diametru 30 cm.',
   (SELECT id FROM categories WHERE slug='baloane'),
   3500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['argintiu'],
   ARRAY['/assets/products/balon-latex-argintiu.webp'], TRUE, 'baloane-latex', FALSE),
  ('balon-latex-auriu-2',
   'Balon latex Auriu 2',
   'Balon din latex, culoare auriu (nuanța 2), diametru 30 cm.',
   (SELECT id FROM categories WHERE slug='baloane'),
   3500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-latex-auriu-2.webp'], TRUE, 'baloane-latex', FALSE),
  ('balon-latex-auriu',
   'Balon latex Auriu',
   'Balon din latex, culoare auriu, diametru 30 cm.',
   (SELECT id FROM categories WHERE slug='baloane'),
   3500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-latex-auriu.webp'], TRUE, 'baloane-latex', FALSE),
  ('balon-latex-bleu',
   'Balon latex Bleu',
   'Balon din latex, culoare bleu, diametru 30 cm.',
   (SELECT id FROM categories WHERE slug='baloane'),
   3500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['albastru'],
   ARRAY['/assets/products/balon-latex-bleu.webp'], TRUE, 'baloane-latex', FALSE),
  ('balon-latex-crem',
   'Balon latex Crem',
   'Balon din latex, culoare crem, diametru 30 cm.',
   (SELECT id FROM categories WHERE slug='baloane'),
   3500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['crem'],
   ARRAY['/assets/products/balon-latex-crem.webp'], TRUE, 'baloane-latex', FALSE),
  ('balon-latex-negru',
   'Balon latex Negru',
   'Balon din latex, culoare negru, diametru 30 cm.',
   (SELECT id FROM categories WHERE slug='baloane'),
   3500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['negru'],
   ARRAY['/assets/products/balon-latex-negru.webp'], TRUE, 'baloane-latex', FALSE),
  ('balon-latex-roz',
   'Balon latex Roz',
   'Balon din latex, culoare roz, diametru 30 cm.',
   (SELECT id FROM categories WHERE slug='baloane'),
   3500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['roz'],
   ARRAY['/assets/products/balon-latex-roz.webp'], TRUE, 'baloane-latex', FALSE),
  ('balon-latex-verde-pasta',
   'Balon latex Verde Pasta',
   'Balon din latex, culoare verde pastel, diametru 30 cm.',
   (SELECT id FROM categories WHERE slug='baloane'),
   3500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['verde'],
   ARRAY['/assets/products/balon-latex-verde-pasta.webp'], TRUE, 'baloane-latex', FALSE),
  ('balon-latex-verde',
   'Balon latex Verde',
   'Balon din latex, culoare verde, diametru 30 cm.',
   (SELECT id FROM categories WHERE slug='baloane'),
   3500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['verde'],
   ARRAY['/assets/products/balon-latex-verde.webp'], TRUE, 'baloane-latex', FALSE),
  ('balon-folie-litera-a',
   'Balon Folie Litera A',
   'Balon folie, litera A, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-a.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-b',
   'Balon Folie Litera B',
   'Balon folie, litera B, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-b.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-c',
   'Balon Folie Litera C',
   'Balon folie, litera C, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-c.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-d',
   'Balon Folie Litera D',
   'Balon folie, litera D, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-d.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-e',
   'Balon Folie Litera E',
   'Balon folie, litera E, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-e.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-f',
   'Balon Folie Litera F',
   'Balon folie, litera F, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-f.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-g',
   'Balon Folie Litera G',
   'Balon folie, litera G, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-g.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-h',
   'Balon Folie Litera H',
   'Balon folie, litera H, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-h.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-i',
   'Balon Folie Litera I',
   'Balon folie, litera I, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-i.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-j',
   'Balon Folie Litera J',
   'Balon folie, litera J, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-j.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-k',
   'Balon Folie Litera K',
   'Balon folie, litera K, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-k.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-l',
   'Balon Folie Litera L',
   'Balon folie, litera L, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-l.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-m',
   'Balon Folie Litera M',
   'Balon folie, litera M, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-m.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-n',
   'Balon Folie Litera N',
   'Balon folie, litera N, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-n.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-o',
   'Balon Folie Litera O',
   'Balon folie, litera O, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-o.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-p',
   'Balon Folie Litera P',
   'Balon folie, litera P, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-p.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-q',
   'Balon Folie Litera Q',
   'Balon folie, litera Q, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-q.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-r',
   'Balon Folie Litera R',
   'Balon folie, litera R, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-r.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-s',
   'Balon Folie Litera S',
   'Balon folie, litera S, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-s.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-t',
   'Balon Folie Litera T',
   'Balon folie, litera T, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-t.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-u',
   'Balon Folie Litera U',
   'Balon folie, litera U, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-u.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-v',
   'Balon Folie Litera V',
   'Balon folie, litera V, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-v.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-w',
   'Balon Folie Litera W',
   'Balon folie, litera W, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-w.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-x',
   'Balon Folie Litera X',
   'Balon folie, litera X, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-x.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-y',
   'Balon Folie Litera Y',
   'Balon folie, litera Y, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-y.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-litera-z',
   'Balon Folie Litera Z',
   'Balon folie, litera Z, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-litera-z.webp'], TRUE, 'folie-litera', FALSE),
  ('balon-folie-cifra-0-argintiu',
   'Balon Folie Cifra 0',
   'Balon folie, cifra 0, argintiu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['argintiu'],
   ARRAY['/assets/products/balon-folie-cifra-0-argintiu.webp'], TRUE, 'numar-argintiu', FALSE),
  ('balon-folie-cifra-1-argintiu',
   'Balon Folie Cifra 1',
   'Balon folie, cifra 1, argintiu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['argintiu'],
   ARRAY['/assets/products/balon-folie-cifra-1-argintiu.webp'], TRUE, 'numar-argintiu', FALSE),
  ('balon-folie-cifra-2-argintiu',
   'Balon Folie Cifra 2',
   'Balon folie, cifra 2, argintiu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['argintiu'],
   ARRAY['/assets/products/balon-folie-cifra-2-argintiu.webp'], TRUE, 'numar-argintiu', FALSE),
  ('balon-folie-cifra-3-argintiu',
   'Balon Folie Cifra 3',
   'Balon folie, cifra 3, argintiu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['argintiu'],
   ARRAY['/assets/products/balon-folie-cifra-3-argintiu.webp'], TRUE, 'numar-argintiu', FALSE),
  ('balon-folie-cifra-4-argintiu',
   'Balon Folie Cifra 4',
   'Balon folie, cifra 4, argintiu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['argintiu'],
   ARRAY['/assets/products/balon-folie-cifra-4-argintiu.webp'], TRUE, 'numar-argintiu', FALSE),
  ('balon-folie-cifra-5-argintiu',
   'Balon Folie Cifra 5',
   'Balon folie, cifra 5, argintiu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['argintiu'],
   ARRAY['/assets/products/balon-folie-cifra-5-argintiu.webp'], TRUE, 'numar-argintiu', FALSE),
  ('balon-folie-cifra-6-argintiu',
   'Balon Folie Cifra 6',
   'Balon folie, cifra 6, argintiu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['argintiu'],
   ARRAY['/assets/products/balon-folie-cifra-6-argintiu.webp'], TRUE, 'numar-argintiu', FALSE),
  ('balon-folie-cifra-7-argintiu',
   'Balon Folie Cifra 7',
   'Balon folie, cifra 7, argintiu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['argintiu'],
   ARRAY['/assets/products/balon-folie-cifra-7-argintiu.webp'], TRUE, 'numar-argintiu', FALSE),
  ('balon-folie-cifra-8-argintiu',
   'Balon Folie Cifra 8',
   'Balon folie, cifra 8, argintiu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['argintiu'],
   ARRAY['/assets/products/balon-folie-cifra-8-argintiu.webp'], TRUE, 'numar-argintiu', FALSE),
  ('balon-folie-cifra-9-argintiu',
   'Balon Folie Cifra 9',
   'Balon folie, cifra 9, argintiu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['argintiu'],
   ARRAY['/assets/products/balon-folie-cifra-9-argintiu.webp'], TRUE, 'numar-argintiu', FALSE),
  ('balon-folie-cifra-0-auriu',
   'Balon Folie Cifra 0',
   'Balon folie, cifra 0, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-cifra-0-auriu.webp'], TRUE, 'numar-auriu', FALSE),
  ('balon-folie-cifra-1-auriu',
   'Balon Folie Cifra 1',
   'Balon folie, cifra 1, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-cifra-1-auriu.webp'], TRUE, 'numar-auriu', FALSE),
  ('balon-folie-cifra-2-auriu',
   'Balon Folie Cifra 2',
   'Balon folie, cifra 2, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-cifra-2-auriu.webp'], TRUE, 'numar-auriu', FALSE),
  ('balon-folie-cifra-3-auriu',
   'Balon Folie Cifra 3',
   'Balon folie, cifra 3, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-cifra-3-auriu.webp'], TRUE, 'numar-auriu', FALSE),
  ('balon-folie-cifra-4-auriu',
   'Balon Folie Cifra 4',
   'Balon folie, cifra 4, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-cifra-4-auriu.webp'], TRUE, 'numar-auriu', FALSE),
  ('balon-folie-cifra-5-auriu',
   'Balon Folie Cifra 5',
   'Balon folie, cifra 5, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-cifra-5-auriu.webp'], TRUE, 'numar-auriu', FALSE),
  ('balon-folie-cifra-6-auriu',
   'Balon Folie Cifra 6',
   'Balon folie, cifra 6, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-cifra-6-auriu.webp'], TRUE, 'numar-auriu', FALSE),
  ('balon-folie-cifra-7-auriu',
   'Balon Folie Cifra 7',
   'Balon folie, cifra 7, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-cifra-7-auriu.webp'], TRUE, 'numar-auriu', FALSE),
  ('balon-folie-cifra-8-auriu',
   'Balon Folie Cifra 8',
   'Balon folie, cifra 8, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-cifra-8-auriu.webp'], TRUE, 'numar-auriu', FALSE),
  ('balon-folie-cifra-9-auriu',
   'Balon Folie Cifra 9',
   'Balon folie, cifra 9, auriu, înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/balon-folie-cifra-9-auriu.webp'], TRUE, 'numar-auriu', FALSE),
  ('balon-folie-cifra-0-roz-auriu',
   'Balon Folie Cifra 0',
   'Balon folie, cifra 0, roz auriu (rose gold), înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu','roz','roz-auriu'],
   ARRAY['/assets/products/balon-folie-cifra-0-roz-auriu.webp'], TRUE, 'numar-roz-auriu', FALSE),
  ('balon-folie-cifra-1-roz-auriu',
   'Balon Folie Cifra 1',
   'Balon folie, cifra 1, roz auriu (rose gold), înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu','roz','roz-auriu'],
   ARRAY['/assets/products/balon-folie-cifra-1-roz-auriu.webp'], TRUE, 'numar-roz-auriu', FALSE),
  ('balon-folie-cifra-2-roz-auriu',
   'Balon Folie Cifra 2',
   'Balon folie, cifra 2, roz auriu (rose gold), înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu','roz','roz-auriu'],
   ARRAY['/assets/products/balon-folie-cifra-2-roz-auriu.webp'], TRUE, 'numar-roz-auriu', FALSE),
  ('balon-folie-cifra-3-roz-auriu',
   'Balon Folie Cifra 3',
   'Balon folie, cifra 3, roz auriu (rose gold), înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu','roz','roz-auriu'],
   ARRAY['/assets/products/balon-folie-cifra-3-roz-auriu.webp'], TRUE, 'numar-roz-auriu', FALSE),
  ('balon-folie-cifra-4-roz-auriu',
   'Balon Folie Cifra 4',
   'Balon folie, cifra 4, roz auriu (rose gold), înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu','roz','roz-auriu'],
   ARRAY['/assets/products/balon-folie-cifra-4-roz-auriu.webp'], TRUE, 'numar-roz-auriu', FALSE),
  ('balon-folie-cifra-5-roz-auriu',
   'Balon Folie Cifra 5',
   'Balon folie, cifra 5, roz auriu (rose gold), înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu','roz','roz-auriu'],
   ARRAY['/assets/products/balon-folie-cifra-5-roz-auriu.webp'], TRUE, 'numar-roz-auriu', FALSE),
  ('balon-folie-cifra-6-roz-auriu',
   'Balon Folie Cifra 6',
   'Balon folie, cifra 6, roz auriu (rose gold), înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu','roz','roz-auriu'],
   ARRAY['/assets/products/balon-folie-cifra-6-roz-auriu.webp'], TRUE, 'numar-roz-auriu', FALSE),
  ('balon-folie-cifra-7-roz-auriu',
   'Balon Folie Cifra 7',
   'Balon folie, cifra 7, roz auriu (rose gold), înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu','roz','roz-auriu'],
   ARRAY['/assets/products/balon-folie-cifra-7-roz-auriu.webp'], TRUE, 'numar-roz-auriu', FALSE),
  ('balon-folie-cifra-8-roz-auriu',
   'Balon Folie Cifra 8',
   'Balon folie, cifra 8, roz auriu (rose gold), înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu','roz','roz-auriu'],
   ARRAY['/assets/products/balon-folie-cifra-8-roz-auriu.webp'], TRUE, 'numar-roz-auriu', FALSE),
  ('balon-folie-cifra-9-roz-auriu',
   'Balon Folie Cifra 9',
   'Balon folie, cifra 9, roz auriu (rose gold), înălțime 100 cm. Umflat cu heliu: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1500, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu','roz','roz-auriu'],
   ARRAY['/assets/products/balon-folie-cifra-9-roz-auriu.webp'], TRUE, 'numar-roz-auriu', FALSE),
  ('lumanari-tort-albastre',
   'Lumânări Tort Albastre',
   'Lumânări decorative pentru tort, culoare albastru, set de 6 bucăți.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1000, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['alb','albastru'],
   ARRAY['/assets/products/lumanari-tort-albastre.webp'], TRUE, 'lumanari-tort', FALSE),
  ('lumanari-tort-negre',
   'Lumânări Tort Negre',
   'Lumânări decorative pentru tort, culoare negru, set de 6 bucăți.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1000, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['negru'],
   ARRAY['/assets/products/lumanari-tort-negre.webp'], TRUE, 'lumanari-tort', FALSE),
  ('lumanari-tort-roz-gold',
   'Lumânări Tort Roz Gold',
   'Lumânări decorative pentru tort, culoare roz gold, set de 6 bucăți.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1000, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['roz'],
   ARRAY['/assets/products/lumanari-tort-roz-gold.webp'], TRUE, 'lumanari-tort', FALSE),
  ('lumanari-tort-roz-neon',
   'Lumânări Tort Roz Neon',
   'Lumânări decorative pentru tort, culoare roz neon, set de 6 bucăți.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1000, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['roz'],
   ARRAY['/assets/products/lumanari-tort-roz-neon.webp'], TRUE, 'lumanari-tort', FALSE),
  ('lumanari-tort-argintii',
   'Lumânări Tort Argintii',
   'Lumânări decorative pentru tort, culoare argintiu, set de 6 bucăți.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1000, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['argintiu'],
   ARRAY['/assets/products/lumanari-tort-argintii.webp'], TRUE, 'lumanari-tort', FALSE),
  ('lumanari-tort-rosii',
   'Lumânări Tort Roșii',
   'Lumânări decorative pentru tort, culoare roșu, set de 6 bucăți.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1000, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['/assets/products/lumanari-tort-rosii.webp'], TRUE, 'lumanari-tort', FALSE),
  ('lumanare-tort-cupa-trofeu',
   'Lumânare Tort Cupă Trofeu',
   'Lumânare decorativă pentru tort, model cupă trofeu, auriu, 1 bucată.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1000, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/lumanare-tort-cupa-trofeu.webp'], TRUE, 'lumanari-tort', FALSE),
  ('lumanare-tort-inima-argintie',
   'Lumânare Tort Inimă Argintie',
   'Lumânare decorativă pentru tort, model inimă cu mesaj "Happy Birthday", argintiu, 1 bucată.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1000, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['argintiu'],
   ARRAY['/assets/products/lumanare-tort-inima-argintie.webp'], TRUE, 'lumanari-tort', FALSE),
  ('lumanare-tort-inima-aurie',
   'Lumânare Tort Inimă Aurie',
   'Lumânare decorativă pentru tort, model inimă cu mesaj "Happy Birthday", auriu, 1 bucată.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1000, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/lumanare-tort-inima-aurie.webp'], TRUE, 'lumanari-tort', FALSE),
  ('lumanare-tort-minge-fotbal',
   'Lumânare Tort Minge Fotbal',
   'Lumânare decorativă pentru tort, model minge de fotbal, alb-negru, 1 bucată.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1000, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['alb','negru'],
   ARRAY['/assets/products/lumanare-tort-minge-fotbal.webp'], TRUE, 'lumanari-tort', FALSE),
  ('lumanare-tort-stea-argintie',
   'Lumânare Tort Stea Argintie',
   'Lumânare decorativă pentru tort, model stea cu mesaj "Happy Birthday", argintiu, 1 bucată.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1000, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['argintiu'],
   ARRAY['/assets/products/lumanare-tort-stea-argintie.webp'], TRUE, 'lumanari-tort', FALSE),
  ('lumanare-tort-stea-aurie',
   'Lumânare Tort Stea Aurie',
   'Lumânare decorativă pentru tort, model stea cu mesaj "Happy Birthday", auriu, 1 bucată.',
   (SELECT id FROM categories WHERE slug='baloane'),
   1000, NULL, 100, NULL,
   ARRAY[]::text[], ARRAY['auriu'],
   ARRAY['/assets/products/lumanare-tort-stea-aurie.webp'], TRUE, 'lumanari-tort', FALSE),
  ('pachet-baloane-aniversare-1-an',
   'Pachet baloane aniversare 1 an',
   'Balon cifra 1 albastru (heliu) + buchet: 6 baloane simple, 1 stea, 2 inimi (heliu). Livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='baloane'),
   20000, NULL, 100, NULL,
   ARRAY['aniversare'], ARRAY['alb','albastru'],
   ARRAY['/assets/products/pachet-baloane-aniversare-1-an.webp'], TRUE, 'pachet-baloane', FALSE),
  ('pachet-baloane-aniversare-5-ani',
   'Pachet baloane aniversare 5 ani',
   'Balon cifra 5 roz-auriu (heliu) + 10 baloane simple pastel multicolore (heliu).',
   (SELECT id FROM categories WHERE slug='baloane'),
   20000, NULL, 100, NULL,
   ARRAY['aniversare'], ARRAY['auriu','roz'],
   ARRAY['/assets/products/pachet-baloane-aniversare-5-ani.webp'], TRUE, 'pachet-baloane', FALSE),
  ('pachet-baloane-aniversare-18-ani',
   'Pachet baloane aniversare 18 ani',
   '2 baloane cifre aurii (heliu) + 10 baloane simple auriu/argintiu/negru (heliu).',
   (SELECT id FROM categories WHERE slug='baloane'),
   25000, NULL, 100, NULL,
   ARRAY['aniversare','majorat'], ARRAY['argintiu','auriu','negru'],
   ARRAY['/assets/products/pachet-baloane-aniversare-18-ani.webp'], TRUE, 'pachet-baloane', FALSE),
  ('pachet-baloane-aniversare-25-ani',
   'Pachet baloane aniversare 25 ani',
   '2 baloane cifre argintii (heliu) + 10 baloane simple roz/alb/roz-sidefat (heliu).',
   (SELECT id FROM categories WHERE slug='baloane'),
   25000, NULL, 100, NULL,
   ARRAY['aniversare'], ARRAY['alb','roz'],
   ARRAY['/assets/products/pachet-baloane-aniversare-25-ani.webp'], TRUE, 'pachet-baloane', FALSE),
  ('pachet-baloane-bride-petrecere-burlacite',
   'Pachet baloane Bride (petrecere burlăcițe)',
   '5 litere BRIDE argintii + 20 baloane albe cu heliu (tavan) + 20 baloane albe cu aer (decor).',
   (SELECT id FROM categories WHERE slug='baloane'),
   49000, NULL, 100, NULL,
   ARRAY['nunta','cerere'], ARRAY['alb'],
   ARRAY['/assets/products/pachet-baloane-bride-petrecere-burlacite.webp'], TRUE, 'pachet-baloane', FALSE),
  ('set-baloane-baby-shower-fetita',
   'Set baloane Baby Shower Fetiță',
   '5 baloane folie: 1 figurină bebeluș, 2 stele roz, 2 rotunde "Little Princess".',
   (SELECT id FROM categories WHERE slug='baloane'),
   0, NULL, 0, NULL,
   ARRAY['botez'], ARRAY['roz'],
   ARRAY['/assets/products/set-baloane-baby-shower-fetita.webp'], FALSE, 'set-baloane', FALSE),
  ('set-baloane-baby-shower-baietel',
   'Set baloane Baby Shower Băiețel',
   '5 baloane folie: 1 figurină bebeluș, 2 stele albastre, 2 rotunde "Little Prince".',
   (SELECT id FROM categories WHERE slug='baloane'),
   0, NULL, 0, NULL,
   ARRAY['botez'], ARRAY['alb'],
   ARRAY['/assets/products/set-baloane-baby-shower-baietel.webp'], FALSE, 'set-baloane', FALSE),
  ('set-baloane-litere-casa-de-piatra',
   'Set baloane litere "Casa de Piatră"',
   '11 litere folie argintii, text "CASA DE PIATRA".',
   (SELECT id FROM categories WHERE slug='baloane'),
   0, NULL, 0, NULL,
   ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['/assets/products/set-baloane-litere-casa-de-piatra.webp'], FALSE, 'set-baloane', FALSE),
  ('set-baloane-litere-la-multi-ani',
   'Set baloane litere "La Mulți Ani"',
   'Litere folie argintii, text "LA MULTI ANI".',
   (SELECT id FROM categories WHERE slug='baloane'),
   0, NULL, 0, NULL,
   ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['/assets/products/set-baloane-litere-la-multi-ani.webp'], FALSE, 'set-baloane', FALSE),
  ('set-baloane-litere-welcome',
   'Set baloane litere "Welcome"',
   '7 litere folie argintii, text "WELCOME".',
   (SELECT id FROM categories WHERE slug='baloane'),
   0, NULL, 0, NULL,
   ARRAY['aniversare'], ARRAY[]::text[],
   ARRAY['/assets/products/set-baloane-litere-welcome.webp'], FALSE, 'set-baloane', FALSE),
  ('set-5-baloane-folie-olaf-frozen',
   'Set 5 baloane folie Olaf Frozen',
   '5 baloane folie: 1 Olaf, 2 stele albastre, 2 rotunde cu personaje Frozen.',
   (SELECT id FROM categories WHERE slug='baloane'),
   0, NULL, 0, NULL,
   ARRAY[]::text[], ARRAY['alb','roz'],
   ARRAY['/assets/products/set-5-baloane-folie-olaf-frozen.webp'], FALSE, 'set-baloane', FALSE),
  ('set-5-baloane-folie-frozen-elsa',
   'Set 5 baloane folie Frozen Elsa',
   '5 baloane folie: 1 portret oval Elsa (mov), 2 inimi mov, 2 rotunde cu personaje Frozen.',
   (SELECT id FROM categories WHERE slug='baloane'),
   0, NULL, 0, NULL,
   ARRAY[]::text[], ARRAY['roz','mov'],
   ARRAY['/assets/products/set-5-baloane-folie-frozen-elsa.webp'], FALSE, 'set-baloane', FALSE)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  price_cents = EXCLUDED.price_cents,
  stock = EXCLUDED.stock,
  occasions = EXCLUDED.occasions,
  colors = EXCLUDED.colors,
  images = EXCLUDED.images,
  is_active = EXCLUDED.is_active,
  product_type = EXCLUDED.product_type;

-- ─── 2. Extra-opțiuni noi pentru baloane (add-on scoped) ───
--  addon_scope = categoriile în care apare opțiunea. NULL/empty = toate (ca add-on-urile vechi de florărie).
INSERT INTO products
  (slug, name, description, category_id, price_cents, stock, is_addon, is_active, addon_scope)
VALUES
  ('addon-heliu',
   'Umflare cu heliu',
   'Balonul se livrează umflat cu heliu. Atenție: livrare doar în Iași.',
   (SELECT id FROM categories WHERE slug='extra'), 5000, 100000, TRUE, TRUE, ARRAY['baloane']),
  ('addon-farfurie-party',
   'Farfurii party (set)',
   'Set farfurii de petrecere asortate.',
   (SELECT id FROM categories WHERE slug='extra'), 1500, 100000, TRUE, TRUE, ARRAY['baloane']),
  ('addon-pahar-party',
   'Pahare party (set)',
   'Set pahare de petrecere asortate.',
   (SELECT id FROM categories WHERE slug='extra'), 1500, 100000, TRUE, TRUE, ARRAY['baloane']),
  ('addon-servetele-party',
   'Șervețele party (set)',
   'Set șervețele de petrecere asortate.',
   (SELECT id FROM categories WHERE slug='extra'), 1000, 100000, TRUE, TRUE, ARRAY['baloane'])
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  price_cents = EXCLUDED.price_cents, addon_scope = EXCLUDED.addon_scope,
  is_active = EXCLUDED.is_active;

-- Add-on-urile vechi (felicitare/bomboane/sampanie/punga) rămân pe florărie:
UPDATE products SET addon_scope = ARRAY['florarie']
  WHERE slug IN ('addon-felicitare','addon-bomboane','addon-sampanie','addon-punga')
    AND addon_scope IS NULL;

-- ─── 3. Baloane demo (fără istoric de comenzi) → scoase din shop ───
--  Păstrează orice produs 'baloane' care a fost comandat (FK order_items).
UPDATE products SET is_active = FALSE
  WHERE category_id = (SELECT id FROM categories WHERE slug='baloane')
    AND is_addon = FALSE
    AND product_type IS NULL
    AND id IN (SELECT product_id FROM order_items);
DELETE FROM products
  WHERE category_id = (SELECT id FROM categories WHERE slug='baloane')
    AND is_addon = FALSE
    AND product_type IS NULL
    AND id NOT IN (SELECT product_id FROM order_items);

COMMIT;
